-- =============================================
-- V1: Baseline schema — captures existing tables
-- created by Hibernate ddl-auto=update
-- =============================================

-- Users table
CREATE TABLE IF NOT EXISTS users (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name            VARCHAR(100)  NOT NULL,
    email           VARCHAR(150)  NOT NULL UNIQUE,
    password_hash   VARCHAR(255)  NOT NULL,
    bio             TEXT,
    profile_image_url VARCHAR(255),
    github_url      VARCHAR(255),
    linkedin_url    VARCHAR(255),
    profile_photo_url TEXT,
    experience_level VARCHAR(50) NOT NULL,
    created_at      TIMESTAMP     NOT NULL DEFAULT now(),
    updated_at      TIMESTAMP     NOT NULL DEFAULT now()
);

-- User skills (ElementCollection — auto-generated by Hibernate)
CREATE TABLE IF NOT EXISTS user_skills (
    user_id     UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    skills      VARCHAR(255),
    PRIMARY KEY (user_id, skills)
);

-- Standalone skills table (Skill entity)
CREATE TABLE IF NOT EXISTS skills (
    id          BIGSERIAL PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    user_id     UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE
);

-- Projects table
CREATE TABLE IF NOT EXISTS projects (
    id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    owner_id         UUID          NOT NULL REFERENCES users(id),
    title            VARCHAR(255)  NOT NULL,
    description      TEXT          NOT NULL,
    domain           VARCHAR(255)  NOT NULL,
    experience_level VARCHAR(50)   NOT NULL,
    status           VARCHAR(50)   NOT NULL DEFAULT 'OPEN',
    team_size        INTEGER       NOT NULL,
    commitment       VARCHAR(255)  NOT NULL,
    repository_url   VARCHAR(255),
    created_at       TIMESTAMP     NOT NULL DEFAULT now(),
    updated_at       TIMESTAMP     NOT NULL DEFAULT now()
);
